variable "vpc_cidr" {}
variable "vpc_name" {}
variable "environment" {}
variable "public_cidr_block" {}
variable "azs" {}
variable "private_cidr_block" {}
variable "owner" {}
variable "costcenter" {}
variable "TeamDL" {}