version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.6.3/terraform_1.6.3_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
  pre_build:
    commands:
      - echo "Initializing Terraform"
      - terraform init
        - terraform init
  build:
    commands:
      - echo "Planning Terraform"
      - terraform workspace select dev
      - terraform init
      - terraform plan -var-file=dev-app.tfvars -out=tfplan.out
      - terraform apply -var-file=dev-app.tfvars --auto-approve
  post_build:
    commands:
      - echo "Applying Terraform"
      - terraform apply -auto-approve tfplan.out
