variable "vpc_cidr_block" {}
variable "tags" {}
variable "vpc_name" {}
variable "env" {}
variable "azs" {}
variable "ec2_ami" {}
variable "ec2_instance_type" {}
variable "public_ec2_count" {}
variable "private_ec2_count" {}
variable "public_ec2_ingress_rules" {}
variable "private_ec2_ingress_rules" {}
variable "volume_data_size" {}
variable "volume_root_size" {}
variable "private_subnet_cidrs" {}
variable "public_subnet_cidrs" {}
variable "private_subnet_amq_cidrs" {}
variable "private_subnet_rmq_cidrs" {}
variable "private_subnet_db_cidrs" {}
variable "key_pair_name" {}

